lib/moviepass_web/router.ex
defmodule MoviepassWeb.Router do
  use MoviepassWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MoviepassWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MoviepassWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController
    get "/oauth/learn", OauthController, :new
    get "/oauth/learn/callback", OauthController, :create
    get "/oauth", OauthController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MoviepassWeb do
  #   pipe_through :api
  # end
end

lib/moviepass_web/views/layout_view.ex
defmodule MoviepassWeb.LayoutView do
  use MoviepassWeb, :view
end

lib/moviepass_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>Moviepass · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <%= if @current_user do %>
              <li><%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete" %></li>
            <% else %>
              <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
              <li><%= link "Login", to: Routes.session_path(@conn, :new) %></li>
              <li><%= link "Login with Learn", to: Routes.oauth_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://www.youtube.com/watch?v=oHg5SJYRHA0" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/moviepass.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>